name = "PATHSolver"
uuid = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
version = "0.6.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinDeps = "≥ 1.0"
ForwardDiff = "≥ 0.9"
julia = "1.3"

[extras]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"

[targets]
test = ["Calculus"]
